# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
 
    
    - name: Download Datadog Java Tracer
      run: |
          mkdir -p $HOME/.datadog
          wget -O $HOME/.datadog/dd-java-agent.jar https://dtdg.co/latest-java-tracer

    - name: Build with Maven
      run: |
        export DD_CIVISIBILITY_ENABLED=true
        export DD_CIVISIBILITY_AGENTLESS_ENABLED=true
        export DD_AGENTLESS_LOG_SUBMISSION_ENABLED=true
        export DD_API_KEY=${{ secrets.DD_API_KEY }}
        export DD_SITE=datadoghq.com
        export DD_ENV=ci
        export DD_SERVICE=my-java-app
        export MAVEN_OPTS=-javaagent:$HOME/.datadog/dd-java-agent.jar 
        mvn clean verify




